"use client";

import { useState } from "react";
import { Conversation } from "./AssistantHome";

interface ShareModalProps {
  conversation: Conversation | null;
  isOpen: boolean;
  onClose: () => void;
  onShowToast: (msg: string) => void;
}

export function ShareModal({
  conversation,
  isOpen,
  onClose,
  onShowToast,
}: ShareModalProps) {
  const [copiedType, setCopiedType] = useState<"link" | "markdown" | "text" | null>(null);

  if (!isOpen || !conversation) return null;

  const chatTitle = conversation.title || "CareerForge AI Mentorship Chat";
  const messages = conversation.messages || [];

  // Generate clean Markdown transcript
  const getMarkdownTranscript = () => {
    let md = `# ${chatTitle}\n*Generated by CareerForge AI Copilot on ${new Date().toLocaleDateString()}*\n\n---\n\n`;
    messages.forEach((m) => {
      const sender = m.role === "user" ? "👤 **User**" : `🤖 **CareerForge AI** (${m.engine || "AI Mentor"})`;
      const time = m.time ? ` *[${m.time}]*` : "";
      md += `### ${sender}${time}\n\n${m.text}\n\n`;
      if (m.attachedDocName) {
        md += `> 📎 *Attached File: ${m.attachedDocName}*\n\n`;
      }
      if (m.intent?.featureTitle) {
        md += `> 🛠️ *Interactive Tool: ${m.intent.featureTitle}*\n\n`;
      }
    });
    return md;
  };

  // Generate plain text transcript
  const getPlainTextTranscript = () => {
    let txt = `=== ${chatTitle} ===\nCareerForge AI Mentorship\nDate: ${new Date().toLocaleString()}\n\n`;
    messages.forEach((m) => {
      const sender = m.role === "user" ? "User" : "CareerForge AI";
      txt += `[${m.time || ""}] ${sender}:\n${m.text}\n\n`;
    });
    return txt;
  };

  // 1. Native Web Share API
  const handleNativeShare = async () => {
    if (typeof navigator !== "undefined" && navigator.share) {
      try {
        const preview = messages
          .filter((m) => m.role === "assistant")
          .map((m) => m.text)
          .slice(-1)[0] || "Career advice from CareerForge AI";

        await navigator.share({
          title: chatTitle,
          text: `Check out this career mentorship session on CareerForge AI:\n\n"${preview.slice(0, 160)}..."`,
          url: window.location.href,
        });
        onShowToast("Shared successfully!");
        onClose();
        return;
      } catch (err: any) {
        if (err.name !== "AbortError") {
          console.warn("Native share failed:", err);
        }
      }
    }
    // Fallback if not supported
    copyLink();
  };

  // 2. Copy Link
  const copyLink = () => {
    if (typeof window !== "undefined") {
      navigator.clipboard.writeText(window.location.href);
      setCopiedType("link");
      onShowToast("🔗 Share link copied to clipboard!");
      setTimeout(() => setCopiedType(null), 2500);
    }
  };

  // 3. Copy Full Markdown
  const copyMarkdown = () => {
    const md = getMarkdownTranscript();
    navigator.clipboard.writeText(md);
    setCopiedType("markdown");
    onShowToast("📋 Formatted chat copied to clipboard!");
    setTimeout(() => setCopiedType(null), 2500);
  };

  // 4. Download Chat File (.md)
  const downloadMarkdown = () => {
    const md = getMarkdownTranscript();
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    const safeTitle = chatTitle.toLowerCase().replace(/[^a-z0-9]/g, "-").slice(0, 30);
    link.href = url;
    link.download = `careerforge-chat-${safeTitle}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    onShowToast("💾 Chat downloaded as Markdown file!");
  };

  // 5. Download Chat File (.txt)
  const downloadPlainText = () => {
    const txt = getPlainTextTranscript();
    const blob = new Blob([txt], { type: "text/plain;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    const safeTitle = chatTitle.toLowerCase().replace(/[^a-z0-9]/g, "-").slice(0, 30);
    link.href = url;
    link.download = `careerforge-chat-${safeTitle}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    onShowToast("💾 Chat downloaded as Text file!");
  };

  // WhatsApp Share Link
  const getWhatsAppShareUrl = () => {
    const shareText = `CareerForge AI Mentorship Chat: ${chatTitle}\n${window.location.href}`;
    return `https://api.whatsapp.com/send?text=${encodeURIComponent(shareText)}`;
  };

  // LinkedIn Share Link
  const getLinkedInShareUrl = () => {
    return `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(window.location.href)}`;
  };

  // Email Share Link
  const getEmailShareUrl = () => {
    const subject = encodeURIComponent(`CareerForge Mentorship: ${chatTitle}`);
    const body = encodeURIComponent(`Here is my CareerForge AI chat transcript:\n\n${getPlainTextTranscript()}`);
    return `mailto:?subject=${subject}&body=${body}`;
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-xs p-4 animate-in fade-in duration-150">
      <div
        className="w-full max-w-lg rounded-2xl border border-neutral-200 bg-white p-6 shadow-2xl space-y-5 animate-in zoom-in-95 duration-150"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between border-b border-neutral-100 pb-3.5">
          <div className="flex items-center gap-2.5">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-neutral-900 text-white shadow-xs">
              <ShareIcon className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-neutral-900">Share Conversation</h2>
              <p className="text-[11px] text-neutral-500 truncate max-w-[280px]">{chatTitle}</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 text-neutral-400 hover:bg-neutral-100 hover:text-neutral-700 transition-colors"
            title="Close modal"
          >
            ✕
          </button>
        </div>

        {/* Chat Stats Preview */}
        <div className="rounded-xl border border-neutral-200/80 bg-neutral-50/70 p-3.5 text-xs text-neutral-700 space-y-1.5">
          <div className="flex items-center justify-between font-semibold text-neutral-800">
            <span>{messages.length} messages in discussion</span>
            <span className="text-[11px] text-neutral-400 font-mono">
              {new Date(conversation.updatedAt).toLocaleDateString()}
            </span>
          </div>
          <p className="text-[11px] text-neutral-500 line-clamp-2">
            {messages[messages.length - 1]?.text || "No messages yet"}
          </p>
        </div>

        {/* Quick Action Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
          {/* Copy Markdown */}
          <button
            type="button"
            onClick={copyMarkdown}
            className="flex items-center justify-center gap-2 rounded-xl border border-neutral-200 bg-white py-2.5 px-3 text-xs font-semibold text-neutral-800 hover:border-neutral-400 hover:bg-neutral-50 transition-all shadow-2xs"
          >
            <CopyIcon className="w-3.5 h-3.5 text-neutral-600" />
            <span>{copiedType === "markdown" ? "Copied to Clipboard!" : "Copy as Markdown"}</span>
          </button>

          {/* Copy Page Link */}
          <button
            type="button"
            onClick={copyLink}
            className="flex items-center justify-center gap-2 rounded-xl border border-neutral-200 bg-white py-2.5 px-3 text-xs font-semibold text-neutral-800 hover:border-neutral-400 hover:bg-neutral-50 transition-all shadow-2xs"
          >
            <LinkIcon className="w-3.5 h-3.5 text-neutral-600" />
            <span>{copiedType === "link" ? "Link Copied!" : "Copy Page Link"}</span>
          </button>

          {/* Download Markdown */}
          <button
            type="button"
            onClick={downloadMarkdown}
            className="flex items-center justify-center gap-2 rounded-xl border border-neutral-200 bg-white py-2.5 px-3 text-xs font-semibold text-neutral-800 hover:border-neutral-400 hover:bg-neutral-50 transition-all shadow-2xs"
          >
            <DownloadIcon className="w-3.5 h-3.5 text-neutral-600" />
            <span>Download .MD File</span>
          </button>

          {/* Download Text */}
          <button
            type="button"
            onClick={downloadPlainText}
            className="flex items-center justify-center gap-2 rounded-xl border border-neutral-200 bg-white py-2.5 px-3 text-xs font-semibold text-neutral-800 hover:border-neutral-400 hover:bg-neutral-50 transition-all shadow-2xs"
          >
            <DownloadIcon className="w-3.5 h-3.5 text-neutral-600" />
            <span>Download .TXT File</span>
          </button>
        </div>

        {/* Social / Direct Channels */}
        <div className="space-y-2 pt-2 border-t border-neutral-100">
          <p className="text-[11px] font-bold uppercase tracking-wider text-neutral-400">Share Directly</p>
          <div className="flex flex-wrap items-center gap-2">
            {/* Native Mobile Share if available */}
            {typeof navigator !== "undefined" && "share" in navigator && (
              <button
                type="button"
                onClick={handleNativeShare}
                className="flex items-center gap-1.5 rounded-lg bg-neutral-900 px-3 py-1.5 text-xs font-medium text-white hover:bg-black transition-colors"
              >
                <ShareIcon className="w-3.5 h-3.5" />
                <span>Device Share</span>
              </button>
            )}

            {/* WhatsApp */}
            <a
              href={getWhatsAppShareUrl()}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 rounded-lg border border-neutral-200 bg-white px-3 py-1.5 text-xs font-medium text-emerald-700 hover:bg-emerald-50 hover:border-emerald-300 transition-colors"
            >
              <span>💬 WhatsApp</span>
            </a>

            {/* LinkedIn */}
            <a
              href={getLinkedInShareUrl()}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 rounded-lg border border-neutral-200 bg-white px-3 py-1.5 text-xs font-medium text-blue-700 hover:bg-blue-50 hover:border-blue-300 transition-colors"
            >
              <span>💼 LinkedIn</span>
            </a>

            {/* Email */}
            <a
              href={getEmailShareUrl()}
              className="flex items-center gap-1.5 rounded-lg border border-neutral-200 bg-white px-3 py-1.5 text-xs font-medium text-neutral-700 hover:bg-neutral-50 transition-colors"
            >
              <span>✉️ Email</span>
            </a>
          </div>
        </div>

        {/* Footer Close */}
        <div className="flex justify-end pt-2">
          <button
            type="button"
            onClick={onClose}
            className="rounded-xl bg-neutral-100 px-4 py-2 text-xs font-semibold text-neutral-700 hover:bg-neutral-200 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── SVG Icons ────────────────────────────────────────────────────────────────

function ShareIcon({ className = "w-4 h-4" }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <circle cx="18" cy="5" r="3" />
      <circle cx="6" cy="12" r="3" />
      <circle cx="18" cy="19" r="3" />
      <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
      <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
    </svg>
  );
}

function CopyIcon({ className = "w-3.5 h-3.5" }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function LinkIcon({ className = "w-3.5 h-3.5" }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  );
}

function DownloadIcon({ className = "w-3.5 h-3.5" }: { className?: string }) {
  return (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  );
}
