import { Course, GitHubProject, RoadmapStep, RoleId, RoleOption } from "./types";

export const roleOptions: RoleOption[] = [
  { id: "frontend", label: "Frontend Engineer", blurb: "Interfaces, interaction, performance" },
  { id: "backend", label: "Backend Engineer", blurb: "Services, data, infrastructure" },
  { id: "data", label: "Data Analyst / Scientist", blurb: "Modeling, pipelines, insight" },
  { id: "product", label: "Product Manager", blurb: "Strategy, roadmaps, execution" },
  { id: "design", label: "Product Designer", blurb: "Research, systems, craft" },
  { id: "devops", label: "DevOps / Platform Engineer", blurb: "Reliability, CI/CD, cloud" },
];

export const roadmaps: Record<RoleId, RoadmapStep[]> = {
  frontend: [
    { title: "Core web fundamentals", detail: "HTML semantics, CSS layout systems, accessibility basics.", skills: ["HTML", "CSS", "A11y"] },
    { title: "JavaScript depth", detail: "Closures, async patterns, the DOM, event loop.", skills: ["JavaScript", "DOM", "Async"] },
    { title: "A modern framework", detail: "Component architecture, state, routing in React or similar.", skills: ["React", "State mgmt", "Routing"] },
    { title: "Tooling & performance", detail: "Bundlers, testing, Core Web Vitals, profiling.", skills: ["Vite/Webpack", "Testing", "Perf"] },
    { title: "System-level thinking", detail: "Design systems, SSR/SSG, edge rendering.", skills: ["Design systems", "Next.js", "SSR"] },
    { title: "Ship & specialize", detail: "Portfolio depth, open source, pick a niche (motion, DX, mobile web).", skills: ["Portfolio", "OSS"] },
  ],
  backend: [
    { title: "Language & fundamentals", detail: "Pick one language deeply; data structures, memory model.", skills: ["Language mastery", "DSA"] },
    { title: "APIs & databases", detail: "REST/GraphQL design, SQL, indexing, transactions.", skills: ["REST", "SQL", "Indexing"] },
    { title: "System design basics", detail: "Caching, queues, load balancing, statelessness.", skills: ["Caching", "Queues", "LB"] },
    { title: "Distributed systems", detail: "Consistency models, sharding, service boundaries.", skills: ["CAP theorem", "Sharding"] },
    { title: "Observability & reliability", detail: "Logging, tracing, SLOs, incident response.", skills: ["Tracing", "SLOs"] },
    { title: "Ship & specialize", detail: "Contribute to a large codebase; pick infra, payments, or platform.", skills: ["Ownership"] },
  ],
  data: [
    { title: "Statistics & Python/R", detail: "Descriptive stats, probability, pandas/dplyr fluency.", skills: ["Statistics", "Python", "Pandas"] },
    { title: "SQL & data modeling", detail: "Joins, window functions, warehouse schemas.", skills: ["SQL", "Modeling"] },
    { title: "Visualization & storytelling", detail: "Dashboards that drive decisions, not just charts.", skills: ["Dashboards", "Storytelling"] },
    { title: "Machine learning foundations", detail: "Regression, classification, evaluation metrics.", skills: ["ML basics", "Evaluation"] },
    { title: "Experimentation", detail: "A/B testing, causal inference basics.", skills: ["A/B testing"] },
    { title: "Ship & specialize", detail: "End-to-end project; pick analytics, ML engineering, or research.", skills: ["Portfolio"] },
  ],
  product: [
    { title: "Product fundamentals", detail: "User research, problem framing, prioritization frameworks.", skills: ["Research", "Prioritization"] },
    { title: "Execution mechanics", detail: "Specs, roadmaps, working with design & engineering.", skills: ["Specs", "Roadmaps"] },
    { title: "Metrics & experimentation", detail: "North-star metrics, funnels, A/B tests.", skills: ["Metrics", "A/B"] },
    { title: "Strategy", detail: "Market sizing, positioning, competitive analysis.", skills: ["Strategy"] },
    { title: "Stakeholder leadership", detail: "Cross-functional influence without authority.", skills: ["Leadership"] },
    { title: "Ship & specialize", detail: "Own a launch end-to-end; pick growth, platform, or 0→1.", skills: ["Ownership"] },
  ],
  design: [
    { title: "Design fundamentals", detail: "Typography, color, layout, visual hierarchy.", skills: ["Typography", "Layout"] },
    { title: "UX research", detail: "Interviews, usability testing, synthesis.", skills: ["Research", "Synthesis"] },
    { title: "Interaction & systems", detail: "Component libraries, interaction states, motion.", skills: ["Design systems", "Motion"] },
    { title: "Prototyping fluency", detail: "Figma depth, rapid prototyping, handoff.", skills: ["Figma", "Prototyping"] },
    { title: "Craft & critique", detail: "Give and receive critique; build a point of view.", skills: ["Critique"] },
    { title: "Ship & specialize", detail: "Case studies with measurable outcomes; pick a domain.", skills: ["Portfolio"] },
  ],
  devops: [
    { title: "Linux & networking", detail: "Shell fluency, TCP/IP basics, DNS.", skills: ["Linux", "Networking"] },
    { title: "Containers & orchestration", detail: "Docker, Kubernetes fundamentals.", skills: ["Docker", "Kubernetes"] },
    { title: "CI/CD", detail: "Build pipelines, automated testing gates, deploy strategies.", skills: ["CI/CD"] },
    { title: "Infrastructure as code", detail: "Terraform/Pulumi, environment parity.", skills: ["IaC"] },
    { title: "Observability & reliability", detail: "Metrics, alerting, on-call practices.", skills: ["Monitoring"] },
    { title: "Ship & specialize", detail: "Own a production platform; pick cloud, security, or SRE.", skills: ["Ownership"] },
  ],
};

export const courseCatalog: Record<RoleId, Course[]> = {
  frontend: [
    { title: "The Complete JavaScript Course", provider: "Udemy", level: "Beginner", rating: 4.7, url: "https://www.udemy.com/course/the-complete-javascript-course/" },
    { title: "Meta Front-End Developer Professional Certificate", provider: "Coursera", level: "Beginner", rating: 4.7, url: "https://www.coursera.org/professional-certificates/meta-front-end-developer" },
    { title: "React - The Complete Guide", provider: "Udemy", level: "Intermediate", rating: 4.6, url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/" },
  ],
  backend: [
    { title: "The Complete Node.js Developer Course", provider: "Udemy", level: "Intermediate", rating: 4.7, url: "https://www.udemy.com/course/the-complete-nodejs-developer-course-2/" },
    { title: "Google IT Automation with Python", provider: "Coursera", level: "Beginner", rating: 4.8, url: "https://www.coursera.org/professional-certificates/google-it-automation" },
    { title: "System Design Interview", provider: "Udemy", level: "Advanced", rating: 4.6, url: "https://www.udemy.com/course/system-design-interview-prep/" },
  ],
  data: [
    { title: "IBM Data Analyst Professional Certificate", provider: "Coursera", level: "Beginner", rating: 4.6, url: "https://www.coursera.org/professional-certificates/ibm-data-analyst" },
    { title: "Python for Data Science and Machine Learning", provider: "Udemy", level: "Intermediate", rating: 4.6, url: "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/" },
    { title: "Deep Learning Specialization", provider: "Coursera", level: "Advanced", rating: 4.9, url: "https://www.coursera.org/specializations/deep-learning" },
  ],
  product: [
    { title: "Digital Product Management", provider: "Coursera", level: "Beginner", rating: 4.6, url: "https://www.coursera.org/specializations/uva-darden-digital-product-management" },
    { title: "Become a Product Manager", provider: "Udemy", level: "Beginner", rating: 4.5, url: "https://www.udemy.com/course/become-a-product-manager-learn-the-skills-earn-the-title/" },
    { title: "Product Management Fundamentals", provider: "Udemy", level: "Intermediate", rating: 4.5, url: "https://www.udemy.com/course/product-management-fundamentals-become-a-pm/" },
  ],
  design: [
    { title: "Google UX Design Professional Certificate", provider: "Coursera", level: "Beginner", rating: 4.8, url: "https://www.coursera.org/professional-certificates/google-ux-design" },
    { title: "The Complete App Design Course", provider: "Udemy", level: "Intermediate", rating: 4.6, url: "https://www.udemy.com/course/ui-ux-web-design-using-adobe-xd/" },
    { title: "Design Systems in Figma", provider: "Udemy", level: "Advanced", rating: 4.7, url: "https://www.udemy.com/course/design-systems-in-figma/" },
  ],
  devops: [
    { title: "Docker & Kubernetes: The Practical Guide", provider: "Udemy", level: "Intermediate", rating: 4.7, url: "https://www.udemy.com/course/docker-kubernetes-the-practical-guide/" },
    { title: "Google Cloud DevOps Engineer", provider: "Coursera", level: "Intermediate", rating: 4.6, url: "https://www.coursera.org/professional-certificates/sre-devops-engineer-google-cloud" },
    { title: "Terraform for the Absolute Beginner", provider: "Udemy", level: "Beginner", rating: 4.6, url: "https://www.udemy.com/course/terraform-beginner-to-advanced/" },
  ],
};

export const marketSkills: Record<RoleId, string[]> = {
  frontend: ["JavaScript", "TypeScript", "React", "CSS", "Accessibility", "Testing", "Performance", "Next.js"],
  backend: ["Node.js", "SQL", "API design", "Docker", "System design", "Caching", "Security", "Python"],
  data: ["SQL", "Python", "Statistics", "Pandas", "Data visualization", "A/B testing", "Machine learning"],
  product: ["Roadmapping", "User research", "SQL", "A/B testing", "Stakeholder management", "Prioritization"],
  design: ["Figma", "User research", "Design systems", "Prototyping", "Accessibility", "Interaction design"],
  devops: ["Kubernetes", "Docker", "Terraform", "CI/CD", "AWS", "Monitoring", "Linux"],
};

export const roleGitHubProjects: Record<RoleId, GitHubProject[]> = {
  frontend: [
    {
      id: "fe-p1",
      name: "React Core Framework",
      repo: "facebook/react",
      url: "https://github.com/facebook/react",
      stars: "228k",
      description: "The library for web and native user interfaces. Master JSX, fiber reconciliation, and hooks.",
      topics: ["React", "JavaScript", "Virtual DOM", "UI Library"],
      difficulty: "Advanced",
    },
    {
      id: "fe-p2",
      name: "Next.js Production Framework",
      repo: "vercel/next.js",
      url: "https://github.com/vercel/next.js",
      stars: "125k",
      description: "The React framework for the Web. Master SSR, ISR, App Router, and server actions.",
      topics: ["Next.js", "React", "TypeScript", "SSR"],
      difficulty: "Intermediate",
    },
    {
      id: "fe-p3",
      name: "Tailwind CSS Utility Engine",
      repo: "tailwindlabs/tailwindcss",
      url: "https://github.com/tailwindlabs/tailwindcss",
      stars: "82k",
      description: "A utility-first CSS framework for rapid UI development with modern CSS design tokens.",
      topics: ["CSS", "Tailwind", "Design Tokens", "PostCSS"],
      difficulty: "Beginner",
    },
    {
      id: "fe-p4",
      name: "shadcn/ui Reusable Components",
      repo: "shadcn-ui/ui",
      url: "https://github.com/shadcn-ui/ui",
      stars: "75k",
      description: "Beautifully designed, accessible components that you can copy and paste into your apps.",
      topics: ["Radix UI", "Tailwind", "Accessibility", "Design System"],
      difficulty: "Intermediate",
    },
  ],
  backend: [
    {
      id: "be-p1",
      name: "System Design Primer",
      repo: "donnemartin/system-design-primer",
      url: "https://github.com/donnemartin/system-design-primer",
      stars: "275k",
      description: "Learn how to design large-scale systems. Covers scalability, microservices, caches, and databases.",
      topics: ["System Design", "Scalability", "Architecture", "Distributed Systems"],
      difficulty: "Advanced",
    },
    {
      id: "be-p2",
      name: "FastAPI Modern Web Framework",
      repo: "fastapi/fastapi",
      url: "https://github.com/fastapi/fastapi",
      stars: "78k",
      description: "High performance, easy to learn, fast to code Python API framework based on standard type hints.",
      topics: ["Python", "API", "Async", "OpenAPI"],
      difficulty: "Beginner",
    },
    {
      id: "be-p3",
      name: "NestJS Scalable Node.js Server",
      repo: "nestjs/nest",
      url: "https://github.com/nestjs/nest",
      stars: "67k",
      description: "A progressive Node.js framework for building efficient, reliable, and enterprise-grade server applications.",
      topics: ["TypeScript", "Node.js", "Architecture", "Microservices"],
      difficulty: "Intermediate",
    },
    {
      id: "be-p4",
      name: "Redis In-Memory Data Store",
      repo: "redis/redis",
      url: "https://github.com/redis/redis",
      stars: "66k",
      description: "In-memory database that persists on disk. The standard for low-latency caching and message queues.",
      topics: ["Database", "Caching", "C", "Performance"],
      difficulty: "Advanced",
    },
  ],
  data: [
    {
      id: "da-p1",
      name: "Scikit-Learn Machine Learning",
      repo: "scikit-learn/scikit-learn",
      url: "https://github.com/scikit-learn/scikit-learn",
      stars: "59k",
      description: "Simple and efficient tools for predictive data analysis and classical machine learning algorithms.",
      topics: ["Machine Learning", "Python", "Data Science", "NumPy"],
      difficulty: "Intermediate",
    },
    {
      id: "da-p2",
      name: "Pandas Data Analysis Toolkit",
      repo: "pandas-dev/pandas",
      url: "https://github.com/pandas-dev/pandas",
      stars: "43k",
      description: "Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures.",
      topics: ["Data Wrangling", "Python", "Analytics", "ETL"],
      difficulty: "Beginner",
    },
    {
      id: "da-p3",
      name: "Hugging Face Transformers",
      repo: "huggingface/transformers",
      url: "https://github.com/huggingface/transformers",
      stars: "133k",
      description: "State-of-the-art Machine Learning for Pytorch, TensorFlow, and JAX supporting LLMs and vision models.",
      topics: ["Deep Learning", "LLMs", "NLP", "PyTorch"],
      difficulty: "Advanced",
    },
    {
      id: "da-p4",
      name: "Apache Spark Unified Engine",
      repo: "apache/spark",
      url: "https://github.com/apache/spark",
      stars: "39k",
      description: "Unified engine for large-scale distributed data analytics, streaming, and machine learning.",
      topics: ["Big Data", "Distributed Computing", "Scala", "Data Lake"],
      difficulty: "Advanced",
    },
  ],
  product: [
    {
      id: "pm-p1",
      name: "GrowthBook Feature Flags & A/B Testing",
      repo: "growthbook/growthbook",
      url: "https://github.com/growthbook/growthbook",
      stars: "6k",
      description: "Open source feature flagging and experimentation platform built for data-driven product teams.",
      topics: ["A/B Testing", "Feature Flags", "Product Analytics", "TypeScript"],
      difficulty: "Intermediate",
    },
    {
      id: "pm-p2",
      name: "Postman API Platform",
      repo: "postmanlabs/postman-app-support",
      url: "https://github.com/postmanlabs/postman-app-support",
      stars: "6k",
      description: "Issue tracking and developer product discovery patterns for the industry standard API collaboration platform.",
      topics: ["API Specs", "Developer Experience", "Product Discovery"],
      difficulty: "Beginner",
    },
    {
      id: "pm-p3",
      name: "Supabase Open Source Firebase Alternative",
      repo: "supabase/supabase",
      url: "https://github.com/supabase/supabase",
      stars: "74k",
      description: "Exemplary developer-first product management: PostgreSQL backend with realtime subscriptions and auth.",
      topics: ["Product Strategy", "BaaS", "Developer Tools", "PostgreSQL"],
      difficulty: "Intermediate",
    },
  ],
  design: [
    {
      id: "des-p1",
      name: "Storybook UI Component Workshop",
      repo: "storybookjs/storybook",
      url: "https://github.com/storybookjs/storybook",
      stars: "84k",
      description: "The industry standard frontend workshop for building UI components and design systems in isolation.",
      topics: ["Design Systems", "Component Driven", "UI/UX", "Documentation"],
      difficulty: "Intermediate",
    },
    {
      id: "des-p2",
      name: "Lucide Icons Library",
      repo: "lucide-icons/lucide",
      url: "https://github.com/lucide-icons/lucide",
      stars: "14k",
      description: "Beautiful & consistent icon toolkit made by the community. A masterclass in scalable SVG design systems.",
      topics: ["Icons", "Design System", "SVG", "Accessibility"],
      difficulty: "Beginner",
    },
    {
      id: "des-p3",
      name: "Adobe React Spectrum Design System",
      repo: "adobe/react-spectrum",
      url: "https://github.com/adobe/react-spectrum",
      stars: "12k",
      description: "A collection of libraries and tools that help you build adaptive, accessible, and robust user experiences.",
      topics: ["Accessibility (a11y)", "Design System", "Adobe", "WCAG"],
      difficulty: "Advanced",
    },
  ],
  devops: [
    {
      id: "dev-p1",
      name: "Kubernetes Production Container Orchestration",
      repo: "kubernetes/kubernetes",
      url: "https://github.com/kubernetes/kubernetes",
      stars: "112k",
      description: "Automating deployment, scaling, and management of containerized applications across cloud clusters.",
      topics: ["Kubernetes", "Cloud Native", "Go", "Orchestration"],
      difficulty: "Advanced",
    },
    {
      id: "dev-p2",
      name: "Terraform Infrastructure as Code",
      repo: "hashicorp/terraform",
      url: "https://github.com/hashicorp/terraform",
      stars: "42k",
      description: "Terraform enables you to safely and predictably create, change, and improve cloud infrastructure.",
      topics: ["IaC", "AWS", "GCP", "Cloud"],
      difficulty: "Intermediate",
    },
    {
      id: "dev-p3",
      name: "Prometheus Monitoring & Alerting Toolkit",
      repo: "prometheus/prometheus",
      url: "https://github.com/prometheus/prometheus",
      stars: "56k",
      description: "The Cloud Native Computing Foundation monitoring system and time series database.",
      topics: ["Monitoring", "SRE", "Observability", "Metrics"],
      difficulty: "Advanced",
    },
    {
      id: "dev-p4",
      name: "Docker Compose Multi-Container Tool",
      repo: "docker/compose",
      url: "https://github.com/docker/compose",
      stars: "34k",
      description: "Define and run multi-container applications with Docker. Essential for local developer environments.",
      topics: ["Docker", "Containers", "DevOps", "Microservices"],
      difficulty: "Beginner",
    },
  ],
};

